// <auto-generated />
using System;
using Fantfoot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fantfoot.Infrastructure.Migrations
{
    [DbContext(typeof(FantfootDbContext))]
    [Migration("20260525004114_AddLocalUser")]
    partial class AddLocalUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Fantfoot.Domain.DraftPick", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsKeeper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverallPickNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Fantfoot.Domain.League", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastReadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousLeagueId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RosterPositions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoringType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRosters")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Fantfoot.Domain.LeagueSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BenchLock")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestBall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyWaivers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyWaiversDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyWaiversHour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DisableAdds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DisableTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastReport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LockedPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxKeepers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxMovements")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinBid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumCommmisioners")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OffseasonAdds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PickDroppable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoffRoundType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoffTeams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoffWeekStart")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveAllowCow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveAllowDnr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveAllowDoubtful")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveAllowOut")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveAllowSus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxiAllowDnr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxiAllowSus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxiAllowVet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxiDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxiSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxiYears")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradeBankSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradeDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradeReviewDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UniversalTicketCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VetoShowVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VetoType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WaiverBudget")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaiverHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaiverType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LeagueSettings");
                });

            modelBuilder.Entity("Fantfoot.Domain.LocalUser", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SleeperUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("Fantfoot.Domain.Matchup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchupId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OpponentPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("OpponentTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Players")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayersPoints")
                        .HasColumnType("TEXT");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectedPoints")
                        .HasColumnType("REAL");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Starters")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartersPoints")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Week", "Season");

                    b.ToTable("Matchups");
                });

            modelBuilder.Entity("Fantfoot.Domain.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FantasyPositions")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjuryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearsExp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Fantfoot.Domain.PlayerStats", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.Property<double>("ProjectedPoints")
                        .HasColumnType("REAL");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stats")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Season", "Week");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("Fantfoot.Domain.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FaabBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PointsAgainst")
                        .HasColumnType("REAL");

                    b.Property<double>("PointsFor")
                        .HasColumnType("REAL");

                    b.Property<string>("Practice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reserve")
                        .HasColumnType("TEXT");

                    b.Property<string>("Roster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Standing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Starters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taxi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ties")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradeBank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaiverPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WaiverPriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fantfoot.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCommissioner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserMessage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
